#Redisson配置
singleServerConfig:
  #  clientName: null
  #  address: "redis://127.0.0.1:6379"
  #  password: null
  #  database: 0
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 5000
  retryAttempts: 2
  retryInterval: 1000
  subscriptionsPerConnection: 5
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 64     # 提高最小空闲连接数，确保高峰期无连接不足
  connectionPoolSize: 512           # 增大连接池以支持更多并发连接
  dnsMonitoringInterval: 5000

threads: 64        # 设置为 2 倍于 CPU 核心数，以支持高并发任务
nettyThreads: 32   # 设置为与 CPU 核心数相等

codec:
  class: "org.redisson.codec.JsonJacksonCodec"
#  class: "org.redisson.codec.FstCodec"
#transportMode: "NIO"
transportMode: "EPOLL"