#Redisson配置
singleServerConfig:
  #  clientName: null
  #  address: "redis://127.0.0.1:6379"
  #  password: null
  #  database: 0
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 3000
  retryAttempts: 2
  retryInterval: 1000
  subscriptionsPerConnection: 5
  subscriptionConnectionMinimumIdleSize: 1
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 24
  connectionPoolSize: 256
  dnsMonitoringInterval: 5000

threads: 16
nettyThreads: 16
codec:
  class: "org.redisson.codec.JsonJacksonCodec"
transportMode: "NIO"