singleServerConfig:
  #  clientName: null
  #  address: "redis://127.0.0.1:6379"
  #  password: null
  #  database: 0
  idleConnectionTimeout: 10000
  connectTimeout: 10000
  timeout: 5000
  retryAttempts: 2
  retryInterval: 1000
  subscriptionsPerConnection: 5
  subscriptionConnectionMinimumIdleSize: 1
#  subscriptionConnectionPoolSize: 5
#  connectionMinimumIdleSize: 4
#  connectionPoolSize: 16
  subscriptionConnectionPoolSize: 50
  connectionMinimumIdleSize: 64
  connectionPoolSize: 512

  dnsMonitoringInterval: 5000

#threads: 4
#nettyThreads: 4
threads: 96
nettyThreads: 48

codec:
  class: "org.redisson.codec.JsonJacksonCodec"
transportMode: "NIO"